version: '3.8'

services:
  timelapse-generator:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/mnt/nfs_share
      - ./tmp:/tmp
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/info"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.25'
          memory: 512M

volumes:
  shared:
    driver: local
  tmp:
    driver: local 